### ISSUE TITLE
Consider migrating code formatting to pre-commit

### ISSUE THREAD

**Issue by BrianPugh** [micropython/micropython-lib#662]
Instead of the bespoke tools/codeformat.py script, it would probably be better to move to the popular [pre-commit](https://pre-commit.com) tool to invoke all linting/formatting/static-analysis tools. Github Actions workflows would also need to be updated to invoke pre-commit.

If migrating to pre-commit sounds good, I can open up a PR.

**Comment by jimmo** [comment]
We've already done this in the [main repo](https://github.com/micropython/micropython/blob/master/.pre-commit-config.yaml) It works very well.

I'm not entirely sure of the history of why the codeformat.py script in this repo has so much extra logic (which the equivalent main repo script doesn't) but I suspect all that can all be removed if we're using it primarily from pre-commit. It also doesn't need the .c file handling.

(I'd like to keep tools/codeformat.py though as it's a convenient and consistent way that works in both repos)

**Comment by BrianPugh** [comment]
Any reason why we cannot ditch the codeformat.py in both repos and put the logic directly in .pre-commit-config.yaml? Consistent way to manually run in both repos would be `pre-commit run --all`. For example, something like the following might reach party with codeformat.py and verifygitlog.py in the main micropython repo

```
repos:

  - repo: local
    hooks:
      - id: uncrustify
        name: Uncrustify
        entry: uncrustify
        args: ['-c', 'tools/uncrustify.cfg', '--no-backup', '-l', 'C']
        language: system
        files: # TODO add PATHS
        exclude: # TODO add EXCLUSIONS

  - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
        - id: gitlint
          # TODO: add config here

  - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.265
      hooks:
        - id: ruff
```
